# Generated by Django 3.2.25 on 2024-11-07 01:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Dish',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('category', models.CharField(choices=[('starter', 'Закуски'), ('main', 'Основные блюда'), ('dessert', 'Десерты'), ('drink', 'Напитки')], max_length=50)),
                ('image', models.ImageField(blank=True, null=True, upload_to='dishes/')),
            ],
        ),
    ]
