# Generated by Django 5.1 on 2024-12-01 05:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_alter_reservation_options_and_more'),
        ('main', '0005_customuser_email'),
    ]

    operations = [
    ]
